version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tripify_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tripify_db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: travelmate_backend
    depends_on:
      - db
    ports:
      - "8386:8386"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mysql_data: